#define TF_PSA_CRYPTO_CONFIG_VERSION 0x01000000

#define PSA_WANT_ALG_CTR 1
#define PSA_WANT_ALG_GCM 1
#define PSA_WANT_ALG_SHA_256 1
#define PSA_WANT_KEY_TYPE_AES 1

#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_EXIT_ALT
#define MBEDTLS_PLATFORM_FPRINTF_ALT

#define MBEDTLS_PLATFORM_SNPRINTF_ALT

#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_PLATFORM_ZEROIZE_ALT
#define MBEDTLS_CHECK_RETURN_WARNING
#define MBEDTLS_DEPRECATED_WARNING
#define TF_PSA_CRYPTO_VERSION
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_PSA_BUILTIN_GET_ENTROPY
#define MBEDTLS_AESNI_C
#define MBEDTLS_AESCE_C
#define MBEDTLS_HAVE_ASM
