#!/usr/bin/env python3

# generate_test_driver.py
#
# Copyright The Mbed TLS Contributors
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

"""
Generate a TF-PSA-Crypto test driver
"""
import argparse
import fnmatch
import sys

from fnmatch import fnmatch
from pathlib import Path
from typing import Iterable, List

import framework_scripts_path # pylint: disable=unused-import
from mbedtls_framework import build_tree

def iter_code_files(root : Path) -> Iterable[Path]:
    for ext in (".c", ".h"):
        yield from root.rglob(f"*{ext}")

def get_src_relpaths(builtin: Path) -> List[Path]:
    """
    Return the paths of the *.c or *.h files to copy from builtin.
    All *.c and *h files but the ones whose basename match one of the
    exclude patterns. The paths returned are relative to builtin.
    """
    exclude_patterns = (
        "asn1*",
        "base64*",
        "crypto_builtin_key_derivation.h",
        "lmots*",
        "lms.c",
        "md.c",
        "memory_buffer_alloc.c",
        "nist_kw.c",
        "pem.c",
        "pk*",
        "platform*",
        "threading*",
    )

    out = []
    for file in iter_code_files(builtin):
        if not any(fnmatch(file.name, pattern) for pattern in exclude_patterns):
            out.append(file.relative_to(builtin))
    out.sort()
    return out

def get_dst_relpaths(src_relpaths: List[Path], driver: str) -> List[Path]:
    """
    Return the paths of the *.c or *.h generated by the script.
    The paths returned are relative to the `<dst_dir>/<driver>` directory.
    Same paths as in src_relpaths but the substitution of `mbedtls` with
    `driver` in `include/mbedtls/...` paths.
    """
    out = []
    for path in src_relpaths:
        parts = list(path.parts)
        if parts[0] == "include" and parts[1] == "mbedtls":
            parts[1] = driver
        out.append(Path(*parts))

    return out

def main():
    """
    Main function of this program
    """
    parser = argparse.ArgumentParser(description="Clone partially drivers/builtin tree, rewrite header inclusions and prefix some C identifiers.")

    parser.add_argument("--dst-dir", default="drivers", metavar="DST_DIR",
        help="Destination directory.\n"
             " - If absolute, used as-is.\n"
             " - If relative, interpreted relative to the repository root.\n"
             f"Default: %(default)s")
    parser.add_argument("--driver", default="libtestdriver1", metavar="DRIVER",
        help="Test driver name (default: %(default)s).")
    parser.add_argument('--list-vars-for-cmake', nargs="?", const="__AUTO__", metavar="FILE",
        help="Generate a file to be included from a CMakeLists.txt.\n"
             "The file defines CMake list variables with the script's inputs/outputs files.\n"
             "If FILE is omitted, the output name defaults to '<DRIVER>-list-vars.cmake'.")

    args = parser.parse_args()

    if not build_tree.looks_like_tf_psa_crypto_root("."):
        raise RuntimeError("This script must be run from TF-PSA-Crypto root.")

    builtin = Path("drivers/builtin")
    if not builtin.is_dir():
        raise RuntimeError("Do not find expected drivers/builtin directory.")
    src_relpaths = get_src_relpaths(builtin)

    dst_dir = Path(args.dst_dir)
    if not dst_dir.is_dir():
        raise RuntimeError(f"Do not find expected {args.dst_dir} directory.")

    if args.list_vars_for_cmake:
        fname = f"{args.driver}-list-vars.cmake" \
                if args.list_vars_for_cmake == "__AUTO__" else args.list_vars_for_cmake

        with open(dst_dir / fname, "w") as f:
            f.write(f"set({args.driver}_input_files " + \
                     " ".join(str(path) for path in src_relpaths) + ")\n\n")
            f.write(f"set({args.driver}_output_files " + \
                     " ".join(str(args.driver / path) for path in get_dst_relpaths(src_relpaths, args.driver)) + ")\n\n")
            f.write(f"set({args.driver}_output_c_files " + \
                     " ".join(str(args.driver / path) for path in src_relpaths if path.suffix == ".c") + ")")
        return

if __name__ == "__main__":
    sys.exit(main())
