#!/usr/bin/env python3

# generate_test_driver.py
#
# Copyright The Mbed TLS Contributors
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

"""
Generate a TF-PSA-Crypto test driver
"""
import argparse
import fnmatch
import itertools
import re
import shutil
import subprocess
import sys

from config import TFPSACryptoConfig
from fnmatch import fnmatch
from pathlib import Path
from typing import Iterable, List, Set

import framework_scripts_path # pylint: disable=unused-import
from mbedtls_framework import build_tree

def iter_code_files(root : Path) -> Iterable[Path]:
    for ext in (".c", ".h"):
        yield from root.rglob(f"*{ext}")

def get_src_relpaths(builtin: Path) -> List[Path]:
    """
    Return the paths of the *.c or *.h files to copy from builtin.
    All *.c and *h files but the ones whose basename match one of the
    exclude patterns. The paths returned are relative to builtin.
    """
    exclude_patterns = (
        "asn1*",
        "base64*",
        "crypto_builtin_key_derivation.h",
        "lmots*",
        "lms.c",
        "md.c",
        "memory_buffer_alloc.c",
        "nist_kw.c",
        "pem.c",
        "pk*",
        "platform*",
        "threading*",
    )

    out = []
    for file in iter_code_files(builtin):
        if not any(fnmatch(file.name, pattern) for pattern in exclude_patterns):
            out.append(file.relative_to(builtin))
    out.sort()
    return out

def get_dst_relpaths(src_relpaths: List[Path], driver: str) -> List[Path]:
    """
    Return the paths of the *.c or *.h generated by the script.
    The paths returned are relative to the `<dst_dir>/<driver>` directory.
    Same paths as in src_relpaths but the substitution of `mbedtls` with
    `driver` in `include/mbedtls/...` paths.
    """
    out = []
    for path in src_relpaths:
        parts = list(path.parts)
        if parts[0] == "include" and parts[1] == "mbedtls":
            parts[1] = driver
        out.append(Path(*parts))

    return out

def create_test_driver_tree(builtin: Path, src_relpaths: List[Path], test_driver_dir: Path):
    for src_relpath in src_relpaths:
        dst = test_driver_dir / src_relpath
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(builtin / src_relpath, dst)
    return

def rewrite_includes_in_file(file: Path, headers: List[str], driver: str):
    include_line_re = re.compile(
        r'^\s*#\s*include\s*([<"])\s*mbedtls/([^>"]+)\s*([>"])', re.MULTILINE
    )
    text = file.read_text(encoding="utf-8")
    changed = False

    def repl(m: re.Match) -> str:
        nonlocal changed
        header = m.group(2)
        if header in headers:
            changed = True
            return f'#include {m.group(1)}{driver}/{header}{m.group(3)}'
        return m.group(0)

    new_text = include_line_re.sub(repl, text)
    if changed:
        file.write_text(new_text, encoding="utf-8")
    return

def run_ctags(files: Iterable[Path]) -> Set[str]:
    result = subprocess.run(
        ["ctags", "-x", "--language-force=C", "--c-kinds=defgpstuv"] + \
        [str(f) for f in files],
        capture_output=True,
        text=True,
        check=True
    )
    identifiers = set()
    for line in result.stdout.splitlines():
        identifiers.add(line.split()[0])

    return identifiers

def get_external_identifiers() -> Set[str]:
    """
    Get from public and core headers the identifiers that the driver built-in
    code may reference but does not define.
    """
    directories = ( "core", "include" )
    files = itertools.chain.from_iterable(Path(directory).rglob("*.h") \
                                          for directory in directories)
    identifiers = run_ctags(files)

    # MBEDTLS_PRIVATE is returned as a prototype by ctags when used in
    # structure members. Just remove it.
    identifiers.remove("MBEDTLS_PRIVATE")

    # ctags ignores the configuration options that are commented in
    # crypto_config.h. Ensure we have all of them.
    identifiers |= set(TFPSACryptoConfig().settings)

    return identifiers

def prefix_identifiers_in_file(file: Path, identifiers: Set[str], driver: str):
    identifier_re = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")

    text = file.read_text(encoding="utf-8")
    changed = False

    def repl(m: re.Match) -> str:
        nonlocal changed
        identifier = m.group(0)
        if identifier in identifiers:
            changed = True
            prefix = driver.upper() if identifier[0].isupper() else driver.lower()
            return f"{prefix}_{identifier}"
        return identifier

    new_text = identifier_re.sub(repl, text)
    if changed:
        file.write_text(new_text, encoding="utf-8")
    return

def prefix_test_driver_identifiers(test_driver_dir: Path, driver: str,
                                   external_identifiers: Set[str]):
    prefixes = (
        "MBEDTLS_",
        "PSA_",
        "TF_PSA_CRYPTO_",
        "mbedtls_",
        "psa_",
        "tf_psa_crypto_",
    )

    identifiers = run_ctags(iter_code_files(test_driver_dir))
    identifiers_to_prefix = set()
    for identifier in identifiers:
        if any(identifier.startswith(prefix) for prefix in prefixes) and \
           identifier not in external_identifiers:
            identifiers_to_prefix.add(identifier)

    forced_identifiers = {
        "MBEDTLS_AESCE_C",
        "MBEDTLS_AESNI_C",
        "MBEDTLS_ECP_LIGHT",
        "MBEDTLS_ECP_NIST_OPTIM",
        "MBEDTLS_ECP_RESTARTABLE",
    }

    for identifier in forced_identifiers:
        identifiers_to_prefix.add(identifier)

    for identifier in external_identifiers:
        if identifier.startswith("PSA_WANT_"):
            identifiers_to_prefix.add(identifier.replace("PSA_WANT_", "MBEDTLS_PSA_ACCEL_", 1))

    for f in iter_code_files(test_driver_dir):
        prefix_identifiers_in_file(f, identifiers_to_prefix, driver)

    return

def main():
    """
    Main function of this program
    """
    parser = argparse.ArgumentParser(description="Clone partially drivers/builtin tree, rewrite header inclusions and prefix some C identifiers.")

    parser.add_argument("--dst-dir", default="drivers", metavar="DST_DIR",
        help="Destination directory.\n"
             " - If absolute, used as-is.\n"
             " - If relative, interpreted relative to the repository root.\n"
             f"Default: %(default)s")
    parser.add_argument("--driver", default="libtestdriver1", metavar="DRIVER",
        help="Test driver name (default: %(default)s).")
    parser.add_argument('--list-vars-for-cmake', nargs="?", const="__AUTO__", metavar="FILE",
        help="Generate a file to be included from a CMakeLists.txt.\n"
             "The file defines CMake list variables with the script's inputs/outputs files.\n"
             "If FILE is omitted, the output name defaults to '<DRIVER>-list-vars.cmake'.")

    args = parser.parse_args()

    if not build_tree.looks_like_tf_psa_crypto_root("."):
        raise RuntimeError("This script must be run from TF-PSA-Crypto root.")

    builtin = Path("drivers/builtin")
    if not builtin.is_dir():
        raise RuntimeError("Do not find expected drivers/builtin directory.")
    src_relpaths = get_src_relpaths(builtin)

    dst_dir = Path(args.dst_dir)
    if not dst_dir.is_dir():
        raise RuntimeError(f"Do not find expected {args.dst_dir} directory.")

    if args.list_vars_for_cmake:
        fname = f"{args.driver}-list-vars.cmake" \
                if args.list_vars_for_cmake == "__AUTO__" else args.list_vars_for_cmake

        with open(dst_dir / fname, "w") as f:
            f.write(f"set({args.driver}_input_files " + \
                     " ".join(str(path) for path in src_relpaths) + ")\n\n")
            f.write(f"set({args.driver}_output_files " + \
                     " ".join(str(args.driver / path) for path in get_dst_relpaths(src_relpaths, args.driver)) + ")\n\n")
            f.write(f"set({args.driver}_output_c_files " + \
                     " ".join(str(args.driver / path) for path in src_relpaths if path.suffix == ".c") + ")")
        return

    #Step 1: Copy selected builtin source files to <dst_dir>/<driver>
    test_driver_dir = Path(args.dst_dir) / args.driver
    if test_driver_dir.exists():
        shutil.rmtree(test_driver_dir)
    create_test_driver_tree(builtin, src_relpaths, test_driver_dir)

    #Step 2: Rename test driver include directory and update header inclusions
    #        accordingly.
    test_driver_include_dir = test_driver_dir / "include" / args.driver
    (test_driver_dir / "include" / "mbedtls").rename(test_driver_include_dir)
    headers = {
        f.relative_to(test_driver_include_dir).as_posix() \
        for f in test_driver_include_dir.rglob("*.h")
    }
    for f in iter_code_files(test_driver_dir):
        rewrite_includes_in_file(f, headers, args.driver)

    #Step 3: Get from public and core headers the set of identifiers that the
    #        driver built-in code may reference but do not define.
    external_identifiers = get_external_identifiers()

    #Step 4
    prefix_test_driver_identifiers(test_driver_dir, args.driver, external_identifiers)

if __name__ == "__main__":
    sys.exit(main())
