#!/usr/bin/env python3

# generate_test_driver.py
#
# Copyright The Mbed TLS Contributors
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

"""
Generate a TF-PSA-Crypto test driver
"""
import itertools
import sys

from fnmatch import fnmatch
from pathlib import Path
from typing import Iterable, List, Set

import scripts_path # pylint: disable=unused-import
from mbedtls_framework import build_tree
from mbedtls_framework import test_driver

from config import TFPSACryptoConfig

EXCLUDE_FILES = {
    "asn1*",
    "base64*",
    "crypto_builtin_key_derivation.h",
    "lmots*",
    "lms.c",
    "md.c",
    "memory_buffer_alloc.c",
    "nist_kw.c",
    "pem.c",
    "pk*",
    "platform*",
    "threading*",
}

IDENTIFIER_PREFIXES = {
    "MBEDTLS_",
    "PSA_",
    "TF_PSA_CRYPTO_",
    "mbedtls_",
    "psa_",
    "tf_psa_crypto_",
}

def iter_code_files(root: Path) -> Iterable[Path]:
    """
    Iterate over all "*.c" and "*.h" files found recursively under the `include`
    and `src` subdirectories of `root`.
    """
    for directory in ("include", "src"):
        directory_path = root / directory
        for ext in (".c", ".h"):
            yield from directory_path.rglob(f"*{ext}")

def get_src_relpaths(builtin: Path, exclude_files: Set[str]) -> List[Path]:
    """
    Return the relative paths of all *.c and *.h files under `builtin`,
    excluding those whose names match any of the patterns in `exclude_files`.

    The returned paths are relative to `builtin`.
    """

    out = []
    for file in iter_code_files(builtin):
        if not any(fnmatch(file.name, pattern) for pattern in exclude_files):
            out.append(file.relative_to(builtin))
    out.sort()
    return out

def get_dst_relpaths(src_relpaths: List[Path], driver: str) -> List[Path]:
    """
    Return the relative paths of the *.c and *.h files generated by the script.

    These paths are the same as in `src_relpaths`, except that occurrences of
    `mbedtls` in `include/mbedtls/...` paths are replaced with `driver`.

    The returned paths are relative to `dst_dir`.
    """

    out = []
    for path in src_relpaths:
        parts = list(path.parts)
        if parts[0] == "include" and parts[1] == "mbedtls":
            parts[1] = driver
        out.append(Path(*parts))

    return out

def get_external_identifiers() -> Set[str]:
    """
    Get from public and core headers the identifiers that the driver built-in
    code may reference but does not define.
    """
    directories = ("core", "include")
    files = itertools.chain.from_iterable(Path(directory).rglob("*.h") \
                                          for directory in directories)
    identifiers = set()
    for file in files:
        identifiers.update(test_driver.run_ctags(file))

    # MBEDTLS_PRIVATE is returned as a prototype by ctags when used in
    # structure members. Just remove it.
    identifiers.remove("MBEDTLS_PRIVATE")

    # ctags ignores the configuration options that are commented in
    # crypto_config.h. Ensure we have all of them.
    identifiers |= set(TFPSACryptoConfig().settings)

    return identifiers

def main():
    """
    Main function of this program
    """
    parser = test_driver.get_parsearg_base()
    parser.add_argument('--list-vars-for-cmake', nargs="?", const="__AUTO__", metavar="FILE",
                        help="Generate a file to be included from a CMakeLists.txt.\n"
                        "The file defines CMake list variables with the script's\n"
                        "inputs/outputs files. If FILE is omitted, the output \n"
                        "name defaults to '<DRIVER>-list-vars.cmake'.")

    args = parser.parse_args()

    if not build_tree.looks_like_tf_psa_crypto_root("."):
        raise RuntimeError("This script must be run from TF-PSA-Crypto root.")

    builtin = Path("drivers/builtin")
    if not builtin.is_dir():
        raise RuntimeError("Do not find expected drivers/builtin directory.")
    src_relpaths = get_src_relpaths(builtin, EXCLUDE_FILES)

    dst_dir = Path(args.dst_dir)
    if not dst_dir.is_dir():
        raise RuntimeError(f"Do not find expected {args.dst_dir} directory.")

    if args.list_vars_for_cmake:
        fname = f"{args.driver}-list-vars.cmake" \
                if args.list_vars_for_cmake == "__AUTO__" else args.list_vars_for_cmake

        with open(dst_dir / fname, "w") as f:
            f.write(f"set({args.driver}_input_files " + \
                     " ".join(str(path) for path in src_relpaths) + ")\n\n")
            f.write(f"set({args.driver}_files " + \
                    " ".join(str(path) \
                    for path in get_dst_relpaths(src_relpaths, args.driver)) + ")\n\n")
            f.write(f"set({args.driver}_src_files " + \
                    " ".join(str(path) \
                    for path in src_relpaths if path.suffix == ".c") + ")")
        return

    #Step 1: Build the test driver tree from `drivers/builtin`
    generator = test_driver.TestDriverGenerator(dst_dir, args.driver)
    generator.build_tree(builtin, EXCLUDE_FILES)

    #Step 2: Prefix the identifiers exposed by the built-in driver.
    identifiers = generator.get_identifiers_with_prefixes(IDENTIFIER_PREFIXES)
    external_identifiers = get_external_identifiers()
    identifiers.difference_update(external_identifiers)

    # MBEDTLS_ECP_LIGHT is defined in tf-psa-crypto/private/crypto_adjust_config_support.h
    # if MBEDTLS_PK_PARSE_EC_EXTENDED or MBEDTLS_PK_PARSE_EC_COMPRESSED is enabled.
    # It thus appears in 'external_identifiers' but is a built-in driver identifier
    # that should be renamed thus force its renaming.
    identifiers.add("MBEDTLS_ECP_LIGHT")

    # MBEDTLS_PSA_ACCEL_ are not defined in the code base. They are supposed to
    # be passed as extra configuration options. We want to prefix them,
    # especially in 'crypto_adjust_config_enable_builtins.h', thus deduce them
    # from the PSA_WANT_ ones and add them to the list of identifiers to
    # prefix in the test driver code.
    for identifier in external_identifiers:
        if identifier.startswith("PSA_WANT_"):
            identifiers.add(identifier.replace("PSA_WANT_", "MBEDTLS_PSA_ACCEL_", 1))

    generator.prefix_identifiers(identifiers)

if __name__ == "__main__":
    sys.exit(main())
